version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ENV['DB_USERNAME']
      POSTGRES_PASSWORD: ENV['DB_PASSWORD']
      POSTGRES_DB: desafio_time_register_brobot_development
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
